### ISSUE TITLE
Tons of errors on import with SuperTiled2Unity

### ISSUE THREAD

**Issue by Stefsteenvoorden** [Seanba/SuperTiled2Unity#94] opened 2019-09-23 15:44 UTC
When I import the SuperTiled2Unity asset pack, my console instantly fills itself with errors.
![errors](https://user-images.githubusercontent.com/29547658/65440646-56098280-de29-11e9-8af7-2a007fa422c5.png) . I think the problem is that the scripts don't recognize the 'Using.UnityEngine.Tilemaps;'
![tilemapserror](https://user-images.githubusercontent.com/29547658/65440868-b0a2de80-de29-11e9-85cd-8feb7699e3ca.png) Does anyone know why, and has anyone else experienced this problem?

**Comment by Stefsteenvoorden** [comment] 2019-09-23 17:20
I fixed it by updating my Unity version, but now I'm left with the colliders not colliding... The colliders are definitely there, but are not colliding with my player.
![collision](https://user-images.githubusercontent.com/29547658/65447619-4002be80-de37-11e9-8cfd-c571b0d5e83c.png)

**Comment by Seanba** [comment] 2019-09-24 05:05
Hi there, @Stefsteenvoorden. Those errors you were getting was due to a missing Tilemap package. The Unity packages are enabled/disabled in the Package Manager on a per-project basis.

![image](https://user-images.githubusercontent.com/6980630/65482371-74d63c00-de5e-11e9-88c4-8ef8419d7d66.png)

As far as the colliders go, it actually looks like they are missing. Are you receiving any other errors or warnings? I can take a quick look if you send me your projects as a Unity Package (sean@seanba.com).

**Comment by Stefsteenvoorden** [comment] 2019-09-24 06:41
That would really be appreciated! Since emailing the package via mail, was too big an attachment, I sent you a link of a shared Google Drive file. Hope that works, else let me know.

**Comment by Seanba** [comment] 2019-09-24 16:21
Thanks. The problem is that the Unity `CompositeCollider2D` geometry is not being scaled with your map (which you have scaled by 7 on the x and y axes).

![image](https://user-images.githubusercontent.com/6980630/65530302-4b98c880-debd-11e9-9bf2-2a7fa12a24de.png)

This is something that Unity should detect for us automatically but it wouldn't be the first time I've had some issues with their composite colliders. I'll see if I can find a fix for this sometime later today. Thanks for letting me know!

**Comment by Stefsteenvoorden** [comment] 2019-09-24 16:47
Aha! I didn't even see those green outlines in the scene editor, ha ha. Thanks for taking the time to find a fix for it, I look forward to it!

**Comment by Seanba** [comment] 2019-09-24 18:56
The collider scaling bug is now fixed with version 1.6.1 of SuperTiled2Unity. Thank you for the bug report.

https://seanba.itch.io/supertiled2unity/devlog/101403/supertiled2unity-version-161

**Closed by Seanba** 2019-09-24 18:56 UTC
