### ISSUE TITLE
Missing texture asset

### ISSUE THREAD

**Issue by KoBeZi** [Seanba/SuperTiled2Unity#67] opened 2019-04-22 07:19 UTC
when I imported the map to unity the first time ，it worked prefecly，all it required is a tmx and  a tsx mathes.But today I try to imported to other project,it filed ,Error is Missing texture asset, missing the png ,it still wont work when I put that png I use to create the tsx for this tmx. "Reimport Tiled Assets"button is not helping either ,so I would really wanted to konw how should I do to fix this

**Comment by rdsdehal** [comment] 2019-04-22 09:01
I m facing the same issue. I m getting this error, 
```
SuperTiled2Unity version: unknown, Unity version: 2018.3.2f1
Missing texture asset: A:/Dawn Maps/tile.png
```
While the texture exists there as well as it exists in the project too.

**Comment by rdsdehal** [comment] 2019-04-22 10:46
Okay, I have fixed it by editing the tmx and tsx by Notepad++ and correcting the path of tilemap.

**Comment by seanb-22ct** [comment] 2019-04-22 14:43
Duplicate of #44

**Comment by seanb-22ct** [comment] 2019-04-22 14:56
Hi there, @KoBeZi. When moving your Tiled files around you have to make sure you keep the relative paths between them intact. My guess is that you changed which folders your files live in when you moved them from one project to another.

If you could answer these two questions it would shed a some light on the solution:
1. What are the errors, specifically, that you are getting? They will tell you where they are expecting a giving asset to exist.
2. What is the actual location of texture asset that SuperTiled2Unity is reporting as missing? You can determine this by clicking on the texture asset in Unity and viewing the status bar at the bottom of your project pane.

![image](https://user-images.githubusercontent.com/18538373/56506670-d62b6500-64e4-11e9-8e90-f1de56d015ed.png)

Eventually, the fix will come down to fixing the TMX or TSX file so that it is looking for your texture file in the right location.

**Comment by Seanba** [comment] 2019-04-28 16:07
These missing assets are a commonly-reported issue with an easy fix. Without further info from the OP I'm going to close the bug for now.

If anyone has ideas on how I could make reporting of such missing assets more obvious then I'm all ears.    Thanks.

**Closed by Seanba** 2019-04-28 16:07 UTC
