### ISSUE TITLE
Collisions not working when updated after import

### ISSUE THREAD

**Issue by icedtommo** [Seanba/SuperTiled2Unity#5] opened 2018-10-22 16:28 UTC
Hello,

Firstly, thanks for such an awesome tool! Really appreciate all your hard work.

I seem to have hit a bit of a bug when I update the map after it has been added to my scene in Unity for the first time.

I have a collision layer in Tiled that I use to highlight all my collisions on the map. When I import it for the first time it works fine, but when I go back and update the map in Tiled with more collisions, they don't work in Unity any more.

I can see the collision polygons in Unity, so I know they're there, and they work if I remove the "Super Collider Script" component from them.

Do you have any idea why this might be?

Happy to provide more details if it would help.

Thanks again,

Matt

**Comment by icedtommo** [comment] 2018-10-22 17:36
I've just tried restarting, but it hasn't fixed it.

I'm not sure if this is related, but I've also noticed that when I bring in the map for the first time and increase the scale, the collision areas don't resize straight away with the rest of the map. but if I change the scale again and then undo it, it goes back to the correct position.

Thanks again for looking into it.

Matt

**Comment by Seanba** [comment] 2018-10-22 18:14
Looking around it looks like there have been several bugs submitted to Unity for this kind of thing. Can you try something though? Select the collision layer in and in the inspector go to the `Composite Collider 2D` components and change the `Generation Type` from `Manual` to `Synchronous`. Does that fix it for you?

In my testing it looks to fix such issues but that's too bad because I am purposely regenerating the composite colliders in code manually and I'd prefer to keep it that way. But let me know if the suggesting above works for you and I'll submit a quick fix. Thanks.

**Comment by Seanba** [comment] 2018-10-22 19:33
If you drag in a new instance of the prefab into your scene those it have the updated geometry? Sorry for the churn on this but it will help me understand what's going on a bit better. :)

**Comment by icedtommo** [comment] 2018-10-22 19:54
No problem! Yes, it updates in the new instance when I drag one in.

**Comment by Seanba** [comment] 2018-10-23 02:32
Hi again. I have confirmed this is bug with Unity's CompositeCollider2D. I have made a small example that demonstrates the issue we are having and I've reported it to Unity. They are usually pretty good at getting back to me quickly on these sort of problems and I'll keep this reported issue updated on any progress.

In the meantime, and I know this sucks, I've been having success with disabling and re-enabling my prefab instance in my scene.

**Comment by icedtommo** [comment] 2018-10-23 06:58
Great, thanks - appreciate you looking into it. I'll try that in the meantime.

**Comment by mzoeller** [comment] 2018-11-14 08:50
I could not get Unity to recreate my colliders by disabling and re-enabling my prefab, nor by manually re-creating the collider. What did work, was setting Generation Type to "Synchronous". I maybe, while we wait for a fix from Unity, just set generation type to sync by default?

**Comment by Seanba** [comment] 2018-11-14 17:43
@mzoeller, what version of Unity did you test this with? FWIW, I had some success with the Synchronous setting when this bug was first reported and was about to submit that as a fix but then it stopped working for me with more testing.

**Comment by mzoeller** [comment] 2018-11-16 09:20
I've only tested this on 2018.2.13.f1

When I change collision information in Tiled and save...
 gentype sync, scene open in Unity: works
 gentype sync, scene not open in Unity: does not work (fix: enable/disable prefab)
 gentype manual, scene open in Unity: does not work (regenerate works, but you need to select different gameobject and then prefab in order to see updated green collision lines)
 gentype manual, scene not open in Unity: does not work (regenerate generates wrong collision, disable+regenerate fixes it)

**Comment by Seanba** [comment] 2018-12-01 19:34
The Unity devs have been able to reproduce this bug and have moved it up the chain for a fix.
https://fogbugz.unity3d.com/default.asp?1093506_ahe9u92nr8fojlcc

I'll update when I know more. Thanks.

**Comment by Seanba** [comment] 2019-03-24 04:43
**Note**: This issue is still not resolved by Unity. However, SuperTiled2Unity 1.2.7 has a hack fix that forces collider geometry to be updated when you press play in the editor or run your game in a build.

I'll keep this issue open until a real fix is provided by Unity. Thanks.

**Comment by Seanba** [comment] 2019-07-20 22:23
At long last I am closing this bug with version 1.5.2 of SuperTiled2Unity. Thanks for the bug report.

**Closed by Seanba** 2019-07-20 22:23 UTC
