### ISSUE TITLE
Sprite Atlas will not work in Unity 2019.3.14 URP

### ISSUE THREAD

**Issue by s4m2d** [Seanba/SuperTiled2Unity#139] opened 2020-05-25 18:00 UTC
This issue will only occure if you use the "Use Sprite Atlas for Tiles" option. I put your example map in Unity and selected the sprite-default materia for better visibility: you can see the result in the picture below. Same happens with my own maps if I check "Use Sprite Atlas for Tiles".  It is reproducable with Unity 2019.3.14f in URP (didn't test without URP)

<img width="1915" alt="spriteatlasissue" src="https://user-images.githubusercontent.com/8577233/82834710-2f24b400-9ec2-11ea-8829-489cd850e0af.png">

**Comment by stoneshih99** [comment] 2020-08-13 17:18
I had the same issue.
It is my solution.
1. Export all assets from the current project. 
2.  Create a new project. 
3. Import assets to the new project.
You can try it.

**Comment by nandovilla** [comment] 2020-10-26 23:47
My solution:

1) In Project Settings -> Graphics, click the gear icon and click Reset;
2) In the same window, click the Clear button;
3) Reimport your tsx files.

Hope it helps!

**Comment by Ruoh3kou** [comment] 2021-07-22 04:21
I had the same issue and recreating new project is not work for me.. 2019 4.16f

**Comment by mpoul1** [comment] 2021-12-09 09:20
Hi I have same issue, solution from nandovilla did not helped. What could be other reason for not working Sprite Atlas ?

**Comment by Seanba** [comment] 2021-12-09 19:16
Hi there, @mpoul1. If you prefer to send me your project I can try to figure out why the sprite atlas options wasn't working for you. You can reach me at sean@seanba.com. Thanks.

**Comment by mpoul1** [comment] 2021-12-10 07:20
Hi, 

thank you for the support. Today I tryed to create brand new empty project in unity + imported your package SuperTiled2Unity + imported tiled data and everything worked perfectly also with Sprite Atlas. So seems I have to deep dive and look at my project and investigate more here why it is not working within my real project.

**Comment by Zelxin** [comment] 2024-03-26 02:42
Hey, I'm currently experiencing this in my project. Did you ever come across the cause?

**Comment by Seanba** [comment] 2024-03-26 16:02
Hi there, @Zelxin. I have not been able to reproduce the problem on my end but given that more folks are reporting issues with sprite atlases I am currently working on a new version of ST2U that doesn't try to do it's own atlasing. Instead, it will create sprites (that are used by tiles) in the source texture. I'll keep you posted.

**Comment by Seanba** [comment] 2024-12-07 05:46
Sprite altasing (and the problems it caused) was removed with `v2.2.0`. Closing for now. Thanks.

**Closed by Seanba** 2024-12-07 05:46 UTC
