### ISSUE TITLE
Missing Prefabs when upgrading from 2018.3 to 2019.4

### ISSUE THREAD

**Issue by Alkanov** [Seanba/SuperTiled2Unity#164] opened 2021-01-04 12:43 UTC
The prefabs that are missing are only the .tsx ones, I have tried reimporting all, deleting the Library folder, obj folder, exporting as .package, and importing into the new project... all failed

More info here: https://forum.unity.com/threads/prefabs-missing-when-upgrading-from-2018-3-to-2019-4.1032607/

**Comment by Alkanov** [comment] 2021-01-04 15:17
Example project https://forum.unity.com/threads/prefabs-missing-when-upgrading-from-2018-3-to-2019-4.1032607/#post-6685807

**Comment by Seanba** [comment] 2021-01-04 18:01
Hi there, @Alkanov. Did you say you had compiler issues you had to fix?

**Comment by Alkanov** [comment] 2021-01-04 18:11
Initially I had, but I managed to replicate the issue without compiler
errors prior to the upgrade to 2019.

Check out the project I attached in the Unity forum which is basically
SuperTiled2Unity in 2018.3 and then it fails to upgrade if you open it with
2019.x or 2020.x

**Comment by Seanba** [comment] 2021-01-04 18:57
Okay, I think I understand now. It's the prefab instance that is somehow losing it's link to the prefab.

I did notice the `Instance ID`s are changing on us which is suspect.

In Unity 2018.3 ...
![image](https://user-images.githubusercontent.com/6980630/103569063-42522600-4e8c-11eb-9ae8-cffb9407e0ca.png)

In Unity 2019.4 ...
![image](https://user-images.githubusercontent.com/6980630/103569127-5eee5e00-4e8c-11eb-9bc3-0ac24cb8c379.png)

**Comment by Alkanov** [comment] 2021-01-04 19:12
Is there a way to fix this even manually? I am in the middle of an upgrade and kinda stuck here

**Comment by Alkanov** [comment] 2021-01-04 20:05
Also tested from 2018.3 to 2018.4 and works fine, but from 2018.4 to 2019.x or 2020.x we get the same missing prefab issue

**Comment by Seanba** [comment] 2021-01-04 20:42
I'll take a look some more but I may need to enter a bug with Unity. I suspect this is an issue unique with Unity's Scripted Importers which was experimental until recently.

As far as a manual fix goes it looks like you can replace the old prefab instances with new ones. What isn't cool with that, however, is changes you made to any of those prefab instances (or any references to them) will be lost.

**Comment by Seanba** [comment] 2021-01-04 20:52
> Also tested from 2018.3 to 2018.4 and works fine, but from 2018.4 to 2019.x or 2020.x we get the same missing prefab issue

I've confirmed that this issue occurs going from 2018.4.30 to 2019.1.0 so it's the divide between 2018 and 2019 Unity that breaks prefab instances for us.

**Comment by Alkanov** [comment] 2021-01-25 15:48
The issue has been replicated by Unity and can be tracked here https://issuetracker.unity3d.com/issues/dot-tmx-file-gameobject-becomes-missing-in-the-scene-when-upgrading-from-2018-dot-4

**Comment by Seanba** [comment] 2022-12-24 22:31
Unity resolved that bug as won't fix. I'll close this for now here as well. Thanks.

**Closed by Seanba** 2022-12-24 22:31 UTC
