### ISSUE TITLE
Import Issues (Unity 2021.3.16f1)

### ISSUE THREAD

**Issue by ghost** [Seanba/SuperTiled2Unity#231] opened 2023-01-15 01:08 UTC
![Capture](https://user-images.githubusercontent.com/89745780/212503733-d50d7377-4dac-4cd3-b282-172b40a012ae.PNG)
When importing tile map it takes forever for the import to finish. I have all of the files that it uses in the .\Assets\Tilesets folder, and I have tried reinstalling SuperTiled2Unity (Awesome project btw, when it works It works great). I am using auto tiles if it helps and when I had it working if I saved without applying the auto tile the same issue would happen but it would fix itself after restarting unity.

**Comment by FlintSkin** [comment] 2023-01-15 01:10
Edit: I am not able to reproduce the error shown in the image above.

**Comment by Seanba** [comment] 2023-01-15 19:35
Hi there, @FlintSkin. Do you have a lot of tilesets? Or tilesets that are large? The initial import can take some time if a lot of big texture atlases have to be made. Those are used to remove seams between tiles but I concede they add to the import time in a way that is troublesome for some projects.

The error you were getting is most likely due to the way your TMX file depends on `Grass.tsx`. It looks like it is looking for that file in `Platformer/Project/Platformer/Assets/Tilesets/Grass.tsx` which seems wrong. Do you still need help figuring that out? If you send me the TMX file I may be able to figure it out.

**Comment by Seanba** [comment] 2024-12-07 05:23
The newer error reporting released with v2.2.0 of ST2U should make it easier to find and fix issues like this. Closing for now but let me know if there are still any problems.

**Closed by Seanba** 2024-12-07 05:23 UTC
