### ISSUE TITLE
Isometric tilelayer doesn't match imagelayer (1.2.4)

### ISSUE THREAD

**Issue by starcid** [Seanba/SuperTiled2Unity#49] opened 2019-03-11 09:29 UTC
Thanks, Seanba.
I reimport the resource with version 1.2.4 and I got the difference result with the 1.2.3 but still incorrect.
In unity(SuperTiled2Unity 1.2.4)
![image](https://user-images.githubusercontent.com/4112149/54113063-73917480-4422-11e9-9a06-067ce1d52a09.png)
You can see that the green tile's positions don't match the image layer's position.

_Originally posted by @starcid in https://github.com/Seanba/SuperTiled2Unity/issues/43#issuecomment-471464650_

**Comment by Seanba** [comment] 2019-03-11 16:09
My apologies. I've re-opened #43 and will close this bug out. I think I know what the problem is.

FWIW, if you ever change your map to be `Infinite` (that's a map property setting) then you're going to see your image layer move around. That sounds like a bug that Bjorn (the author of Tiled) may need to know about.

**Closed by Seanba** 2019-03-11 16:09 UTC
