### ISSUE TITLE
Texture Rectangle is out of bounds

### ISSUE THREAD

**Issue by joshwreford** [Seanba/SuperTiled2Unity#32] opened 2019-01-29 18:09 UTC
I've created a map and tileset in Tiled using 240x240 pixel tiles. 
When I import that into Unity using "Super Tiled2Unity", I get loads of "Texture Rectangle is out of bounds" errors. 

I tried this will a map and tileset that I created using 16x16 pixel tiles and it worked absolutely fine. 

Is there a problem with using ST2U with larger pixel images? I've tried this maybe 20 times now and every time I get the same error. I've tried starting a fresh Unity project and freshly installing "Super Tiled2Unity" but still I'm getting the same issue. 

Please help!

**Comment by joshwreford** [comment] 2019-01-29 18:09
![screenshot 2019-01-29 at 18 08 05](https://user-images.githubusercontent.com/12631096/51929822-0a651d00-23f1-11e9-8e0b-02aa4ec9247b.png)

**Comment by Seanba** [comment] 2019-01-29 19:16
Can you send me your project as a Unity Package? There must be something wrong with the texture atlasing.

Thanks.

**Comment by joshwreford** [comment] 2019-01-30 08:22
Thanks for replying so fast @Seanba !!

I've just sent a zip of the project to sean@seanba.com via WeTransfer. 
The project is pretty much empty apart from the Tilemap etc, so hopefully it should be easy to navigate around.

**Comment by Seanba** [comment] 2019-01-30 17:50
Hi again, @joshwreford. You've uncovered a bug I'll have to work on but in the meantime you can work around it by making sure your imported textures are not being resized.

You have a texture named `la_dungeon_floors_walls` that is 2400x2400 but is being resized to 2048x2048. If you set the max size to 4096 instead then the import will work.

![image](https://user-images.githubusercontent.com/6980630/52001371-dcc9b380-2484-11e9-867f-916dbe5199ca.png)

On another note: I'd keep your Tiled files outside of the SuperTiled2Unity folder. That's just so everything related to that library can stay self-contained. Not a big deal, just good housekeeping, IMHO.

I'll update when I have a real fix for this bug. Thanks for the bug report!

**Comment by joshwreford** [comment] 2019-01-30 18:07
You're a hero @Seanba! I'll try your workaround now. Thanks!

**Comment by joshwreford** [comment] 2019-01-31 14:12
That’s amazing! Thanks a lot. Your fix worked a treat and has saved my game! I was close to giving up!

**Comment by Seanba** [comment] 2019-01-31 16:35
@joshwreford. You're welcome.

On a more personal note: Making games are tough. Keep your scope as small as possible - and don't give up. 👍

**Comment by joshwreford** [comment] 2019-02-12 22:00
Hey @Seanba 

Hate to raise another issue. The fix you gave me above by changing the "max size" was working a treat! But I made some new changes to my Tile Maps and reuploaded the files and I'm having a similar but different issue now. 

I'm getting your lovely new error saying "Texture was imported at a smaller size. Make sure 'Max Size' on xxx.png is at least '4800'. 

But the max size on my png is set to 8192! I've changed it a few times, and tried reimporting all the assets but nothing seems to make a different. I get the same error every time. 

If I drag the map into Unity, I can't see the right images from that TSX. So it's definitely not working (and not just displaying an error.) 

I've just sent the files to your email address via We Transfer. If you can drop them into any old project and see if you get the same error, or know why I might be getting this, I would be so so so so grateful. 

Thanks a million in advance. 
Josh

**Comment by Seanba** [comment] 2019-02-13 00:17
Hi @joshwreford. The issue is that you've resized your source tileset textures but the tilesets still reference the old width, height, and tile count. I'm thinking of ways I can account for this. Stay tuned.

**Comment by joshwreford** [comment] 2019-02-13 09:49
Thanks @Seanba !!

**Comment by Seanba** [comment] 2019-03-07 20:41
My apologies for letting this bug linger but it was fixed with version 1.2.3 of SuperTiled2Unity. Thanks for letting me know about it.

**Closed by Seanba** 2019-03-07 20:41 UTC
